<?php

/**
 * @file
 * Add an URL formatter for image field
 */


/**
 * Implements hook_theme().
 */
function image_url_formatter_theme() {
  return array(
    'image_url_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'path' => NULL,
        'image_style' => NULL,
        'url_type' => NULL,
      ),
    ),
  );
}

/**
 * Returns HTML for an image url field formatter.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An array of image data.
 *   - image_style: An optional image style.
 *   - path: An optional array containing the link 'path' and link 'options'.
 *
 * @ingroup themeable
 */
function theme_image_url_formatter($variables) {
  $item = $variables['item'];

  // Do not output an empty 'title' attribute.
  if (isset($item['title']) && drupal_strlen($item['title']) == 0) {
    unset($item['title']);
  }
  
  $output = file_create_url($item['uri']);
  if ($variables['image_style']) {
    $image['style_name'] = $variables['image_style'];
    $output = image_style_url($image['style_name'], $item['uri']);
  }
  
  $url_type = isset($variables['']) ? $variables['image_style'] : 0;
  if($url_type == 1){
    $output = str_replace($GLOBALS['base_url'], '', $output);
  }
  elseif($url_type == 2){
     $output = str_replace($GLOBALS['base_url'] . '/', '', $output);
  }
  
  if(isset($variables['image_style']))
  // The link path and link options are both optional, but for the options to be
  // processed, the link path must at least be an empty string.
  if (isset($variables['path']['path'])) {
    $path = $variables['path']['path'];
    $options = isset($variables['path']['options']) ? $variables['path']['options'] : array();
    // When displaying an image inside a link, the html option must be TRUE.
    $options['html'] = TRUE;
    $output = l($output, $path, $options);
  }

  return $output;
}
